### ISSUE TITLE
map: players separated by impassable terrain

### ISSUE THREAD

**Issue by xu-kj** [xu-kj/sc1bot#5]
create a test map that is divided into 2 sections blocked by impassable terrain, this allows bot to build buildings and units without having to worry about getting attacked by AI

**Comment by YECHUNAN** [comment]
Map attached. Player 1 have access to resources while player 2 not.

[emptyTestLand.zip](https://github.com/xu-kj/sc1bot/files/6275978/emptyTestLand.zip)

**Comment by YECHUNAN** [comment]
星际1的破烂地图编辑器不让固定初始位置，只能随机分配。我给两边都放了资源，差不多够运营了。
