### ISSUE TITLE
auto-mine minerals

### ISSUE THREAD

**Issue by xu-kj** [xu-kj/sc1bot#9]
[SCV][wiki-SCV]s in previous implementation needs to be manually assigned to mine minerals, add implementation to automate this step

reference:

* https://liquipedia.net/starcraft/Resources
* non-goal: ideal mining, https://tl.net/forum/brood-war/89939-ideal-mining-thoughts

[wiki-SCV]: https://liquipedia.net/starcraft/SCV

**Comment by yuechaohou** [comment]
Resolved.
